const fs = require('fs');
const path = require('path');

// Load from .env file if it exists
const dotenvPath = path.join(__dirname, '..', '.env');
if (fs.existsSync(dotenvPath)) {
  require('dotenv').config({ path: dotenvPath });
}

const supabaseUrl = process.env['SUPABASE_URL'] || 'https://placeholder-not-configured.supabase.co';
const supabaseAnonKey = process.env['SUPABASE_ANON_KEY'] || 'placeholder-key';

if (!process.env['SUPABASE_URL']) {
  console.warn('WARNING: SUPABASE_URL is not set. Create a .env file or set it in your shell.');
}
if (!process.env['SUPABASE_ANON_KEY']) {
  console.warn('WARNING: SUPABASE_ANON_KEY is not set. Create a .env file or set it in your shell.');
}

const content = `// Generated by scripts/generate-env.js — do not edit directly.
export const env = {
  supabaseUrl: '${supabaseUrl}',
  supabaseAnonKey: '${supabaseAnonKey}',
};
`;

const outputPath = path.join(__dirname, '..', 'src', 'environments', 'env.ts');
fs.writeFileSync(outputPath, content, 'utf-8');

console.log(`Environment file written to ${outputPath}`);
if (supabaseUrl !== 'https://placeholder-not-configured.supabase.co') {
  console.log(`Supabase URL: ${supabaseUrl}`);
}
